official_smolvla:
  checkpoint: lerobot/smolvla_base
  checkpoint_strict: false
  override_checkpoint_config: true
  stats_source: dataset
  vlm_model_name: HuggingFaceTB/SmolVLM2-500M-Instruct
  load_vlm_weights: true
  image_feature_keys:
    - observation.images.image
    - observation.images.image2
  tokenizer_max_length: 48
  pad_language_to: longest
  freeze_backbone: false
  policy_overrides:
    num_steps: 10
    n_action_steps: 1
